# Generated by Django 3.2 on 2021-06-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_num',
            field=models.CharField(max_length=40),
        ),
    ]
